/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PredictionMarket } from './PredictionMarket.js';
export * as factories from './factories/index.js';
export { PredictionMarket__factory } from './factories/PredictionMarket__factory.js';