/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PredictionMarketInterface extends Interface {
    getFunction(nameOrSignature: "claimReward" | "claimed" | "createMarket" | "getMarket" | "getOptionTotal" | "getUserStake" | "hasUserClaimed" | "marketCount" | "markets" | "optionTotals" | "owner" | "resolveMarket" | "stakes" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MarketCreated" | "MarketResolved" | "RewardClaimed" | "Voted"): EventFragment;

    encodeFunctionData(functionFragment: 'claimReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createMarket', values: [string, string[], BigNumberish, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOptionTotal', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserStake', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasUserClaimed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'marketCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'markets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'optionTotals', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveMarket', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'stakes', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'claimReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOptionTotal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasUserClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'optionTotals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace MarketCreatedEvent {
      export type InputTuple = [marketId: BigNumberish, question: string, options: string[], deadline: BigNumberish, marketType: BigNumberish, targetPrice: BigNumberish, ticker: string];
      export type OutputTuple = [marketId: bigint, question: string, options: string[], deadline: bigint, marketType: bigint, targetPrice: bigint, ticker: string];
      export interface OutputObject {marketId: bigint, question: string, options: string[], deadline: bigint, marketType: bigint, targetPrice: bigint, ticker: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketResolvedEvent {
      export type InputTuple = [marketId: BigNumberish, winningOption: BigNumberish, reason: string];
      export type OutputTuple = [marketId: bigint, winningOption: bigint, reason: string];
      export interface OutputObject {marketId: bigint, winningOption: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardClaimedEvent {
      export type InputTuple = [marketId: BigNumberish, claimer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, claimer: string, amount: bigint];
      export interface OutputObject {marketId: bigint, claimer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [marketId: BigNumberish, optionIndex: BigNumberish, voter: AddressLike, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, optionIndex: bigint, voter: string, amount: bigint];
      export interface OutputObject {marketId: bigint, optionIndex: bigint, voter: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionMarket;
    waitForDeployment(): Promise<this>;

    interface: PredictionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claimReward: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    createMarket: TypedContractMethod<
      [question: string, options: string[], deadline: BigNumberish, marketType: BigNumberish, targetPrice: BigNumberish, ticker: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    getMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [[string, string[], bigint, boolean, bigint, bigint, bigint, bigint, string] & {question: string, options: string[], deadline: bigint, resolved: boolean, winningOption: bigint, totalPool: bigint, marketType: bigint, targetPrice: bigint, ticker: string }],
      'view'
    >
    

    
    getOptionTotal: TypedContractMethod<
      [marketId: BigNumberish, optionIndex: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getUserStake: TypedContractMethod<
      [marketId: BigNumberish, optionIndex: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    hasUserClaimed: TypedContractMethod<
      [marketId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    marketCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    markets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, boolean, bigint, bigint, boolean, bigint, bigint, string] & {question: string, deadline: bigint, resolved: boolean, winningOption: bigint, totalPool: bigint, exists: boolean, marketType: bigint, targetPrice: bigint, ticker: string }],
      'view'
    >
    

    
    optionTotals: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveMarket: TypedContractMethod<
      [marketId: BigNumberish, winningOption: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    stakes: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [marketId: BigNumberish, optionIndex: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claimReward'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [question: string, options: string[], deadline: BigNumberish, marketType: BigNumberish, targetPrice: BigNumberish, ticker: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [[string, string[], bigint, boolean, bigint, bigint, bigint, bigint, string] & {question: string, options: string[], deadline: bigint, resolved: boolean, winningOption: bigint, totalPool: bigint, marketType: bigint, targetPrice: bigint, ticker: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getOptionTotal'): TypedContractMethod<
      [marketId: BigNumberish, optionIndex: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserStake'): TypedContractMethod<
      [marketId: BigNumberish, optionIndex: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasUserClaimed'): TypedContractMethod<
      [marketId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'marketCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'markets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, boolean, bigint, bigint, boolean, bigint, bigint, string] & {question: string, deadline: bigint, resolved: boolean, winningOption: bigint, totalPool: bigint, exists: boolean, marketType: bigint, targetPrice: bigint, ticker: string }],
      'view'
    >;
getFunction(nameOrSignature: 'optionTotals'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveMarket'): TypedContractMethod<
      [marketId: BigNumberish, winningOption: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakes'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [marketId: BigNumberish, optionIndex: BigNumberish, ],
      [void],
      'payable'
    >;

    getEvent(key: 'MarketCreated'): TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'RewardClaimed'): TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;

    filters: {
      
      'MarketCreated(uint256,string,string[],uint256,uint8,uint256,string)': TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
      MarketCreated: TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
    

      'MarketResolved(uint256,uint8,string)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'RewardClaimed(uint256,address,uint256)': TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
      RewardClaimed: TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
    

      'Voted(uint256,uint8,address,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    
    };
  }